### ISSUE TITLE
fatal error: 'Rtatami.h' file not found during installation

### ISSUE THREAD

**Issue by phoebe-yg** [xiaosaiyao/epiregulon#26]
Hi Xiaosai, 

I tried to install `epiregulon` on macOS Ventura v13.3 (with apple chip).  And I ran into the error below:

> clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/beachmat/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
> clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/beachmat/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c aggregate_across_cells.cpp -o aggregate_across_cells.o
> aggregate_across_cells.cpp:1:10: fatal error: 'Rtatami.h' file not found
> #include "Rtatami.h"
>          ^~~~~~~~~~~
> 1 error generated.
> make: *** [aggregate_across_cells.o] Error 1
> ERROR: compilation failed for package ‘epiregulon’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/epiregulon’
> Warning messages:
> 1: In readLines(old_path) :
>   incomplete final line found on '/Users/pheebs/.R/Makevars'
> 2: In i.p(...) :
>   installation of package ‘/var/folders/qq/vltg2cn173gggch01q6dhy5c0000gn/T//RtmpjwR2Jz/file86941a069acd/epiregulon_0.99.12.tar.gz’ had non-zero exit status

I investigated a little bit. I think it's related to version issue with the dependant package `beachmat`. The current `beachmat` doesn't seem to support `epiregulon`. And the developer version `beachmat` require R 4.4 , which is not official released yet. 

Do you know if there's a way to get around this?

My session info here:

> R version 4.3.3 (2024-02-29)
> Platform: aarch64-apple-darwin20 (64-bit)
> Running under: macOS Ventura 13.3
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
> LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> time zone: America/Los_Angeles
> tzcode source: internal
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>   [1] RColorBrewer_1.1-3     rstudioapi_0.16.0      jsonlite_1.8.8         shape_1.4.6.1         
>   [5] magrittr_2.0.3         spatstat.utils_3.0-4   rmarkdown_2.26         fs_1.6.3              
>   [9] GlobalOptions_0.1.2    vctrs_0.6.5            ROCR_1.0-11            memoise_2.0.1         
>  [13] spatstat.explore_3.2-7 rstatix_0.7.2          usethis_2.2.3          forcats_1.0.0         
>  [17] htmltools_0.5.8.1      curl_5.2.1             broom_1.0.5            sctransform_0.4.1     
>  [21] parallelly_1.37.1      KernSmooth_2.23-22     desc_1.4.3             htmlwidgets_1.6.4     
>  [25] ica_1.0-3              plyr_1.8.9             cachem_1.0.8           plotly_4.10.4         
>  [29] zoo_1.8-12             igraph_2.0.3           mime_0.12              lifecycle_1.0.4       
>  [33] pkgconfig_2.0.3        Matrix_1.6-5           R6_2.5.1               fastmap_1.1.1         
>  [37] fitdistrplus_1.1-11    future_1.33.2          shiny_1.8.1.1          digest_0.6.35         
>  [41] colorspace_2.1-0       ps_1.7.6               patchwork_1.2.0        Seurat_5.0.3          
>  [45] tensor_1.5             RSpectra_0.16-1        irlba_2.3.5.1          pkgload_1.3.4         
>  [49] progressr_0.14.0       fansi_1.0.6            spatstat.sparse_3.0-3  httr_1.4.7            
>  [53] polyclip_1.10-6        abind_1.4-5            compiler_4.3.3         remotes_2.5.0         
>  [57] backports_1.4.1        BiocParallel_1.34.2    carData_3.0-5          fastDummies_1.7.3     
>  [61] pkgbuild_1.4.4         MASS_7.3-60.0.1        sessioninfo_1.2.2      tools_4.3.3           
>  [65] lmtest_0.9-40          zip_2.3.1              httpuv_1.6.15          msigdbr_7.5.1         
>  [69] future.apply_1.11.2    goftest_1.2-3          glue_1.7.0             callr_3.7.6           
>  [73] nlme_3.1-164           promises_1.3.0         grid_4.3.3             Rtsne_0.17            
>  [77] cluster_2.1.6          reshape2_1.4.4         fgsea_1.26.0           generics_0.1.3        
>  [81] gtable_0.3.4           spatstat.data_3.0-4    tidyr_1.3.1            data.table_1.15.4     
>  [85] sp_2.1-3               car_3.1-2              utf8_1.2.4             spatstat.geom_3.2-9   
>  [89] RcppAnnoy_0.0.22       ggrepel_0.9.5          RANN_2.6.1             pillar_1.9.0          
>  [93] stringr_1.5.1          spam_2.10-0            babelgene_22.9         RcppHNSW_0.6.0        
>  [97] ggprism_1.0.5          later_1.3.2            circlize_0.4.16        splines_4.3.3         
> [101] dplyr_1.1.4            lattice_0.22-6         survival_3.5-8         deldir_2.0-4          
> [105] tidyselect_1.2.1       miniUI_0.1.1.1         pbapply_1.7-2          knitr_1.46            
> [109] gridExtra_2.3          scattermore_1.2        xfun_0.43              devtools_2.4.5        
> [113] matrixStats_1.3.0      stringi_1.8.3          lazyeval_0.2.2         yaml_2.3.8            
> [117] evaluate_0.23          codetools_0.2-20       tibble_3.2.1           BiocManager_1.30.22   
> [121] cli_3.6.2              uwot_0.1.16            xtable_1.8-4           reticulate_1.35.0     
> [125] processx_3.8.4         munsell_0.5.1          Rcpp_1.0.12            globals_0.16.3        
> [129] spatstat.random_3.2-3  png_0.1-8              parallel_4.3.3         ellipsis_0.3.2        
> [133] ggplot2_3.5.0          dotCall64_1.1-1        profvis_0.3.8          urlchecker_1.0.1      
> [137] listenv_0.9.1          viridisLite_0.4.2      scales_1.3.0           ggridges_0.5.6        
> [141] openxlsx_4.2.5.2       SeuratObject_5.0.1     leiden_0.4.3.1         purrr_1.0.2           
> [145] rlang_1.1.3            fastmatch_1.1-4        cowplot_1.1.3

**Comment by TomVuod** [comment]
Hello @phoebe-yg could you try to install first `beachmat`? The version in master branch should work in R 4.3.3.

**Comment by xiaosaiyao** [comment]
@phoebe-yg you can also try to install beachmat (3.18 release) from bioconductor directly. We are in the process of submitting epiregulon for bioconductor 3.19 release (subject to package acceptance). If you want to wait a couple of weeks, it hopefully will be available in R4.4/BioC3.19. 

In the mean time, you may be able to install a previous commit without beachmat (https://github.com/xiaosaiyao/epiregulon/commit/44dc4d75262a9a4899692e3810d0ff975a0862e4)

**Comment by phoebe-yg** [comment]
Thanks for your replies! I copied the files in `beachmat/inst/include` from Github to my local directory and it works for me! Hopefully after the R4.4 update in a few weeks, this will no longer be an issue. Thanks!!

**Comment by xiaosaiyao** [comment]
epiregulon and epiregulon.extra are accepted into bioC today and will come out in the BioC 3.19 release
