### ISSUE TITLE
need to do checks for count matrix 

### ISSUE THREAD

**Issue by xiaosaiyao** [xiaosaiyao/epiregulon#31]
@TomVuod please insert a check to make sure that count matrix is in dgCMatrix

**Comment by TomVuod** [comment]
The issue has been addressed by commit [eca043c](https://github.com/xiaosaiyao/epiregulon/commit/eca043c8b2a608f14bb398fc892a27bf4c7512eb). Assay matrices are now coerced to `sparseMatrix`.
