### ISSUE TITLE
gene_symbol argument not incorporated

### ISSUE THREAD

**Issue by xiaosaiyao** [xiaosaiyao/epiregulon#8]
@TomVuod  please replace with  `o$Gene <- rowData(sce_grouped)[o[, 1], gene_symbol]`
https://github.com/xiaosaiyao/epiregulon/blob/a70ef94163ab954bf0b2b6f80a69f6e815477641/R/calculateP2G.R#L144

**Comment by TomVuod** [comment]
Changed.
